# from baseImage:linux distributation
FROM node:alpine
# copy the application or program file into the /app directory of that image
COPY . /app 
# setting the working directory
WORKDIR /app
# this to excute a command
CMD node app.js
# CMD node /app/app.js
